export const INGREDIENTS = [
    {
        name: 'Bananas',
        slug: 'bananas',
        image: require('./ingredients_images/bananas.png'),
        category: 'fruits',
    },
    {
        name: 'Tomatoes',
        slug: 'tomatoes',
        image: require('./ingredients_images/tomatoes.png'),
        category: 'vegetables',
    },
    {
        name: 'Bread',
        slug: 'bread',
        image: require('./ingredients_images/bread.png'),
        category: 'grains',
    },
    {
        name: 'Potatoes',
        slug: 'potatoes',
        image: require('./ingredients_images/potatoes.png'),
        category: 'vegetables',
    },
    {
        name: 'Garlic',
        slug: 'garlic',
        image: require('./ingredients_images/garlic.png'),
        category: 'vegetables',
    },
    {
        name: 'Cow meat',
        slug: 'cow meat',
        image: require('./ingredients_images/cow_meat.png'),
        category: 'meat, animal',
    },
    {
        name: 'Eggs',
        slug: 'eggs',
        image: require('./ingredients_images/eggs.png'),
        category: 'animal',
    },
    {
        name: 'Lettuce',
        slug: 'lettuce',
        image: require('./ingredients_images/lettuce.png'),
        category: 'vegetables',
    },
    {
        name: 'Avocado',
        slug: 'avocado',
        image: require('./ingredients_images/avocado.png'),
        category: 'vegetables',
    },
    {
        name: 'Cheese',
        slug: 'cheese',
        image: require('./ingredients_images/cheese.png'),
        category: 'dairies',
    },
    {
        name: 'Spaghetti',
        slug: 'spaghetti',
        image: require('./ingredients_images/spaghetti.png'),
        category: 'pasta',
    },
    {
        name: 'Sausage',
        slug: 'sausage',
        image: require('./ingredients_images/sausage.png'),
        category: 'meat',
    },
    {
        name: 'Onion',
        slug: 'onion',
        image: require('./ingredients_images/onion.png'),
        category: 'vegetables',
    },
    {
        name: 'Milk',
        slug: 'milk',
        image: require('./ingredients_images/milk.png'),
        category: 'dairies',
    },
    {
        name: 'Flour',
        slug: 'flour',
        image: require('./ingredients_images/flour.png'),
        category: 'grains',
    },
    {
        name: 'Butter',
        slug: 'butter',
        image: require('./ingredients_images/butter.png'),
        category: 'dairies',
    },
    {
        name: 'Baking powder',
        slug: 'baking powder',
        image: require('./ingredients_images/baking_powder.png'),
        category: 'grains',
    },
    {
        name: 'Cilantro',
        slug: 'cilantro',
        image: require('./ingredients_images/cilantro.png'),
        category: 'vegetables',
    },
    {
        name: 'Quinoa',
        slug: 'quinoa',
        image: require('./ingredients_images/quinoa.png'),
        category: 'grains',
    },
    {
        name: 'Vanilla bean',
        slug: 'vanilla bean',
        image: require('./ingredients_images/vanilla.png'),
        category: 'spices',
    },
    {
        name: 'Cinnamon',
        slug: 'cinnamon',
        image: require('./ingredients_images/cinnamon.png'),
        category: 'spices',
    },
    {
        name: 'Chicken',
        slug: 'chicken',
        image: require('./ingredients_images/chicken.png'),
        category: 'meat',
    },
    {
        name: 'Bacon',
        slug: 'bacon',
        image: require('./ingredients_images/bacon.png'),
        category: 'meat',
    },
    {
        name: 'Corn',
        slug: 'corn',
        image: require('./ingredients_images/corn.png'),
        category: 'vegetables',
    },
    {
        name: 'Pepper',
        slug: 'pepper',
        image: require('./ingredients_images/pepper.png'),
        category: 'vegetables',
    },
    {
        name: 'Carrot',
        slug: 'carrot',
        image: require('./ingredients_images/carrot.png'),
        category: 'vegetables',
    },
    {
        name: 'Broccoli',
        slug: 'broccoli',
        image: require('./ingredients_images/brocoli.png'),
        category: 'vegetables',
    },
    {
        name: 'Pumpkin',
        slug: 'pumpkin',
        image: require('./ingredients_images/pumpkin.png'),
        category: 'vegetables',
    },
    {
        name: 'Chard',
        slug: 'chard',
        image: require('./ingredients_images/chard.png'),
        category: 'vegetables',
    },
    {
        name: 'Salmon',
        slug: 'salmon',
        image: require('./ingredients_images/salmon.png'),
        category: 'meat',
    },
    {
        name: 'Pork',
        slug: 'pork',
        image: require('./ingredients_images/pork.png'),
        category: 'meat',
    },
    {
        name: 'Prosciutto',
        slug: 'prosciutto',
        image: require('./ingredients_images/prosciutto.png'),
        category: 'meat',
    },
    {
        name: 'Ham',
        slug: 'ham',
        image: require('./ingredients_images/ham.png'),
        category: 'meat',
    },
    {
        name: 'Apple',
        slug: 'apple',
        image: require('./ingredients_images/apple.png'),
        category: 'fruits',
    },
    {
        name: 'Kiwi',
        slug: 'kiwi',
        image: require('./ingredients_images/kiwi.png'),
        category: 'fruits',
    },
    {
        name: 'Orange',
        slug: 'orange',
        image: require('./ingredients_images/orange.png'),
        category: 'fruits',
    },
    {
        name: 'Watermelon',
        slug: 'watermelon',
        image: require('./ingredients_images/watermelon.png'),
        category: 'fruits',
    },
    {
        name: 'Grapes',
        slug: 'grapes',
        image: require('./ingredients_images/grapes.png'),
        category: 'fruits',
    },
    {
        name: 'Strawberries',
        slug: 'strawberries',
        image: require('./ingredients_images/strawberry.png'),
        category: 'fruits',
    },
    {
        name: 'Blueberries',
        slug: 'blueberries',
        image: require('./ingredients_images/blueberry.png'),
        category: 'fruits',
    },
    {
        name: 'Peach',
        slug: 'peach',
        image: require('./ingredients_images/peach.png'),
        category: 'fruits',
    },
];