export const INGREDIENTS = [
    {
        name: 'Bananas',
        slug: 'bananas',
        image: require('./ingredients_images/bananas.png'),
        category: 'fruits',
    },
    {
        name: 'Tomatoes',
        slug: 'tomatoes',
        image: require('./ingredients_images/tomatoes.png'),
        category: 'vegetables',
    },
    {
        name: 'Bread',
        slug: 'bread',
        image: require('./ingredients_images/bread.png'),
        category: 'grains',
    },
    {
        name: 'Potatoes',
        slug: 'potatoes',
        image: require('./ingredients_images/potatoes.png'),
        category: 'vegetables',
    },
    {
        name: 'Garlic',
        slug: 'garlic',
        image: require('./ingredients_images/garlic.png'),
        category: 'vegeatables',
    },
    {
        name: 'Cow meat',
        slug: 'cow meat',
        image: require('./ingredients_images/cow_meat.png'),
        category: 'meat, animal',
    },
    {
        name: 'Eggs',
        slug: 'eggs',
        image: require('./ingredients_images/eggs.png'),
        category: 'animal',
    },
    {
        name: 'Lettuce',
        slug: 'lettuce',
        image: require('./ingredients_images/lettuce.png'),
        category: 'vegetables',
    },
    {
        name: 'Avocado',
        slug: 'avocado',
        image: require('./ingredients_images/avocado.png'),
        category: 'fruits',
    },
    {
        name: 'Cheese',
        slug: 'cheese',
        image: require('./ingredients_images/cheese.png'),
        category: 'dairies',
    },
    {
        name: 'Spaghetti',
        slug: 'spaghetti',
        image: require('./ingredients_images/spaghetti.png'),
        category: 'pasta',
    },
    {
        name: 'Sausage',
        slug: 'sausage',
        image: require('./ingredients_images/sausage.png'),
        category: 'meat',
    },
    {
        name: 'Onion',
        slug: 'onion',
        image: require('./ingredients_images/onion.png'),
        category: 'vegetables',
    },
    {
        name: 'Milk',
        slug: 'milk',
        image: require('./ingredients_images/milk.png'),
        category: 'dairies',
    },
    {
        name: 'Flour',
        slug: 'flour',
        image: require('./ingredients_images/flour.png'),
        category: 'grains',
    },
    {
        name: 'Butter',
        slug: 'butter',
        image: require('./ingredients_images/butter.png'),
        category: 'dairies',
    },
    {
        name: 'Baking powder',
        slug: 'baking powder',
        image: require('./ingredients_images/baking_powder.png'),
        category: 'grains',
    },
    {
        name: 'Cilantro',
        slug: 'cilantro',
        image: require('./ingredients_images/cilantro.png'),
        category: 'vegetables',
    },
    {
        name: 'Quinoa',
        slug: 'quinoa',
        image: require('./ingredients_images/quinoa.png'),
        category: 'grains',
    },
    {
        name: 'Vanilla bean',
        slug: 'vanilla bean',
        image: require('./ingredients_images/vanilla.png'),
        category: 'spices',
    },
    {
        name: 'Cinnamon',
        slug: 'cinnamon',
        image: require('./ingredients_images/cinnamon.png'),
        category: 'spices',
    },
    {
        name: 'Chicken',
        slug: 'chicken',
        image: require('./ingredients_images/chicken.png'),
        category: 'meat',
    },
    {
        name: 'Bacon',
        slug: 'bacon',
        image: require('./ingredients_images/bacon.png'),
        category: 'meat',
    },

];